# fly.toml app configuration file generated for expotv-frontend
app = "expotv-frontend"
primary_region = "gru"

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
